--Raw Materials
['plastic']                         = {['name'] = 'plastic',                           ['label'] = 'Plastic',                   ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'plastic.png',                 ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Plastic, fantastic?'},
['metalscrap']                      = {['name'] = 'metalscrap',                        ['label'] = 'Metalscrap',                ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'metalscrap.png',              ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Various pieces of metal'},
['copper']                          = {['name'] = 'copper',                            ['label'] = 'Copper',                    ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'copper.png',                  ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Copper, useful for making wires'},
['aluminum']                        = {['name'] = 'aluminum',                          ['label'] = 'Aluminum',                  ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'aluminum.png',                ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'A nice shiny metal'},
['aluminumoxide']                   = {['name'] = 'aluminumoxide',                     ['label'] = 'Aluminum Oxyd',		        ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'aluminumoxide.png',           ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Metal powder'},
['iron']                            = {['name'] = 'iron',                              ['label'] = 'Iron',                      ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'iron.png',                    ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = ''},
['ironoxide']                       = {['name'] = 'ironoxide',                         ['label'] = 'Iron Oxyd',             	['weight'] = 100,          ['type'] = 'item',         ['image'] = 'ironoxide.png',               ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Some metal Powder'},
['steel']                           = {['name'] = 'steel',                             ['label'] = 'Steel',                     ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'steel.png',                   ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'A piece of steel'},
['rubber']                          = {['name'] = 'rubber',                            ['label'] = 'Rubber',                	['weight'] = 100,          ['type'] = 'item',         ['image'] = 'rubber.png',                  ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Useful for creating seals'},
['glass']                           = {['name'] = 'glass',                             ['label'] = 'Glass',                     ['weight'] = 100,          ['type'] = 'item',         ['image'] = 'glass.png',                   ['unique'] = false,         ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'A piece of glass'},

--Scraps
['empty_glass_bottle']              = {['name'] = 'empty_glass_bottle',                 ['label'] = 'Empty glass bottle',   	['weight'] = 750,          ['type'] = 'item',         ['image'] = 'empty_glass_bottle.png',     ['unique'] = false,     	 ['useable'] = false,     ['shouldClose'] = false, 	   ['combinable'] = nil,   ['description'] = 'A dirty glass bottle'},
['empty_plastic_bottle']            = {['name'] = 'empty_plastic_bottle',               ['label'] = 'Empty plastic bottle', 	['weight'] = 750,          ['type'] = 'item',         ['image'] = 'empty_plastic_bottle.png',   ['unique'] = false,     	 ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'A recycled plastic bottle'},
['empty_can']                       = {['name'] = 'empty_can',                          ['label'] = 'Empty can',              	['weight'] = 450,          ['type'] = 'item',         ['image'] = 'empty_can.png',              ['unique'] = false,     	 ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'An aluminum beverage can.'},
['cardboard']                       = {['name'] = 'cardboard',                          ['label'] = 'Cardboard',             	['weight'] = 50,           ['type'] = 'item',         ['image'] = 'cardboard.png',              ['unique'] = false,     	 ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'Some cardboard scraps.'},
['wrapper']                         = {['name'] = 'wrapper',                            ['label'] = 'Wrapper',                  ['weight'] = 50,           ['type'] = 'item',         ['image'] = 'wrapper.png',                ['unique'] = false,     	 ['useable'] = false,     ['shouldClose'] = false,     ['combinable'] = nil,   ['description'] = 'A used candy wrapper.'},
['wire']                       		= {['name'] = 'wire',                               ['label'] = 'Wire',              		['weight'] = 20,           ['type'] = 'item',         ['image'] = 'cable.png',                   ['unique'] = false,         ['useable'] = true,      ['shouldClose'] = true,      ['combinable'] = nil,   ['description'] = 'Construction site cables'},

